### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by joereddington** [iandevlin/iandevlin.github.io#1]
Can I just check - I'm assuming that this code is open licensed per https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses - have I got that right? I couldn't see anything explicit... 

Joe

**Comment by iandevlin** [comment]
I hadn't thought about it to be honest, but since it was written for MDN then it would only be fair if those conditions to which you linked to would apply.
I am the only contributor to it in this case mind you, so an attribute is always welcome.

**Comment by iandevlin** [comment]
Also, if you do anything with it, I'd be very interested in knowing what!

**Comment by joereddington** [comment]
It's a deal :) Will keep you up to date. :)

**Comment by iandevlin** [comment]
Great, thanks!
